### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JoakimSoderberg** [mattn/ansicolor-w32.c#1]
Hello @mattn I was thinking of writing something similar myself, but googled it first... However, I tried it and couldn't get it to work (I had to add `vasprintf` back since that's not available on windows, just noticed I could've simply gone back a commit instead :feelsgood:).

Aside from `vasprintf`, I cannot get this to work at all. The example you give in the Readme doesn't do anything for me on OSX if I try it there, nor does it do anything with aniscolor-w32 on windows. I also tried a simpler `\x1b[22;31m` to make the text red which works fine on OSX, but not on Windows.

Any ideas?

**Comment by mattn** [comment]
I see the issue number is younger than others, do you still get this issue?

**Comment by JoakimSoderberg** [comment]
Yes still not working. I tried printing `"\x1b[22;31mhello\x1b[0m"` and it prints `31mhello`

**Comment by JoakimSoderberg** [comment]
Ah! ofcourse "\x1b[31mhello\x1b[0m" works... So I guess it's the combined attributes using `;` that's the issue.
