### ISSUE TITLE
Unable to fetch package using clib

### ISSUE THREAD

**Issue by daddinuz** [mattn/ansicolor-w32.c#7]
Hi @mattn,
I'm using your library in a project of mine, but I face some troubles when I try to install it using clib.
After some investigations I discovered that the problem is that there is no release tag with version 0.0.1 as referenced in the package.json, so when clib tries to fetch the library at https://raw.githubusercontent.com/mattn/ansicolor-w32.c/0.0.1/ansicolor-w32.h it gets an HTTP 404.
So I was just wondering if you could release the 0.0.1 version in order to fix that :)

**Comment by mattn** [comment]
done. thank you
